"""Make finished_at nullable

Revision ID: ef6d1a4f2e39
Revises: b649a7060859
Create Date: 2026-08-19 14:00:36.842031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d1a4f2e39'
down_revision = 'b649a7060859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('finished_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('finished_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
